- Forcing the kotlin-daemon-client version to `2.3.10`
***

Project is using the Kotlin Gradle Plugin 2.3.10. However, the License plugin brings in the Kotlin BOM for version 2.4.0, which forces a silent upgrade of the kotlin-daemon-client on the Gradle classpath

Because kotlin-compiler-runner (2.3.10) is trying to use kotlin-daemon-client (2.4.0), the method signature for connectAndLease no longer matches, resulting in the NoSuchMethodError.